// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpwtucxdballrgkwezyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wd3R1Y3hkYmFsbHJna3dlenl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNTY3NzIsImV4cCI6MjA1MDYzMjc3Mn0.zlqE6cHearbCsiJrcCIOSizxPEnh4jHHOxWDfSWeQRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);